### ISSUE TITLE
Deprecated: media_buttons_context

### ISSUE THREAD

**Issue by greatknave** [LionSher-Technologies/soliloquy-lite#21]
Per this .org ticket: https://wordpress.org/support/topic/depreciation-message-in-the-plugin

If you edit a category in WP-admin, you can see an error message like this:

“Deprecated: media_buttons_context is deprecated since version 3.5.0! Use media_buttons instead.”

**Comment by dimensionmedia** [comment]
We are already using 'media_buttons' in master. Not sure if this was fixed prior to this ticket. "Edit a category" is also non-Envira behavior, so that's odd. I will say @greatknave @bmilligan15 - call this fixed, maybe notify user in support but at the same time say if they see it again in the future it might be another plugin.
